### ISSUE TITLE
#![no_std] and embedded-hal support

### ISSUE THREAD

**Issue by sajattack** [scholtzan/st7735-rs#1]
Hi there, thanks for your driver, it looks great! Just a suggestion to open it up for use on non-linux boards (ie microcontrollers) -- if you make your driver `#![no_std]`, and replace the `SpiDev` with `embedded_hal::blocking::spi::Write`, it opens up a whole new world of devices that can use your crate. Docs [here](https://docs.rs/embedded-hal/0.2.2/embedded_hal/blocking/spi/trait.Write.html). There is also [linux-embedded-hal](https://crates.io/crates/linux-embedded-hal), so you wouldn't lose linux support. Oh, one more thing, you could use [embedded-graphics](https://crates.io/crates/embedded-graphics) rather than have your own special routines for drawing shapes.

**Comment by scholtzan** [comment]
Hey, thanks for the suggestions! Definitely will look into them.

**Comment by sajattack** [comment]
Let me know if you need any help.

**Comment by scholtzan** [comment]
Forgot about this issue but made this driver `#![no_std]` and added embedded-hal support a while back. I also tested embedded-graphics and found them to make the rendering quite a bit slower.

**Comment by sajattack** [comment]
`alloc` still isn't very embedded friendly and I wanted `embedded-graphics` so I made a fork that rewrote 90% of this driver at https://github.com/sajattack/st7735-lcd-rs
